Keep track of dependency providers
muiriswoulfe/NuGet-Transitive-Dependency-Finder pull request #150
Opened 2021-10-25 11:43 UTC by basilfx

# Pull Request
This PR also includes #149, which is necessary for this to work.

## Summary
This fix keeps track of references to a dependency.

Given the following example:

```
A
  -> B (project)
  -> C (project)
  -> X (package)

B
  -> C (project)
  -> X (package)

C
  -> X (package)
```

When scanning project A, this fix:
- marks B as a 'provider' of C
- marks B and C as a 'provider' of X
- marks C and X as transitive

The logic for top-level dependencies has been slightly altered. This means that for a dependency to be transitive, it must have at least one 'provider'.

## Behavior

### Previous
Providers were not listed, and so were project dependencies.

### New
Providers are shown, and so are project dependencies.

## Breaking Changes
The public API contains a new method:

```diff
+NuGetTransitiveDependencyFinder.Output.Dependency.Via.get -> System.Collections.Generic.ISet<NuGetTransitiveDependencyFinder.Output.Dependency!>!
```

## Testing Undertaken

Without fix:

```
Commencing analysis...
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Writing A/j2wlqag5.tis

  Determining projects to restore...
  All projects are up-to-date for restore.

  Determining projects to restore...
  All projects are up-to-date for restore.

  Determining projects to restore...
  All projects are up-to-date for restore.

A
    .NETCoreApp v5.0
        Newtonsoft.Json v12.0.3

B
    .NETCoreApp v5.0
        Newtonsoft.Json v12.0.3

C
    .NETCoreApp v5.0
        Newtonsoft.Json v12.0.3
```

With fix (including #149):

```
Commencing analysis...
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Writing A/cd4k53de.v4n

  Determining projects to restore...
  All projects are up-to-date for restore.

  Determining projects to restore...
  All projects are up-to-date for restore.

  Determining projects to restore...
  All projects are up-to-date for restore.

A
    .NETCoreApp v5.0
        B v1.0.0
        C v1.0.0 (Transitive)
            B v1.0.0
        X v2.0.0 (Transitive)
            C v1.0.0
            B v1.0.0
        Newtonsoft.Json v12.0.3

B
    .NETCoreApp v5.0
        C v1.0.0
        X v2.0.0 (Transitive)
            C v1.0.0
        Newtonsoft.Json v12.0.3

C
    .NETCoreApp v5.0
        X v2.0.0
        Newtonsoft.Json v12.0.3
```

## Additional Information
Note that X is now correctly marked as a dependency of C. Before, it did not since X was a 'top-level' dependency and therefore never added to the list of dependencies.

2021-10-25 16:23 UTC, muiriswoulfe submitted a review, later dismissed

2021-11-06 17:55 UTC, basilfx commented
Last one, rebased and signed :-)

2021-11-06 20:10 UTC, muiriswoulfe requested changes
Thanks. Could you address the CodeQL issue reported in the build and I'll commit the change?

2021-11-07 22:35 UTC, basilfx commented
CodeQL issue fixed.

2021-11-07 23:12 UTC, muiriswoulfe commented
> CodeQL issue fixed.

Thanks!

2021-11-07 23:12 UTC, muiriswoulfe approved these changes

2021-11-07 23:12 UTC, merged